<?php

use Illuminate\Database\Seeder;

class ConfigurationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'CSP', 'libelle' => 'Etudiant']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'CSP', 'libelle' => 'RSA']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Catégorie', 'libelle' => 'RSA']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Situation', 'libelle' => 'Couple']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Logement', 'libelle' => 'HLM']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Niveau Scolaire', 'libelle' => 'Lycée']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Situation', 'libelle' => 'Célibataire']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Situation', 'libelle' => 'Union libre']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Situation', 'libelle' => 'Marié(e)']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Situation', 'libelle' => 'Divorcé(e)']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Catégorie', 'libelle' => 'MDPH']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Catégorie', 'libelle' => 'PLI']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Logement', 'libelle' => 'SDF']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Logement', 'libelle' => 'Maison']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Logement', 'libelle' => 'Foyer']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Logement', 'libelle' => 'Hebergé/hôtel social']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Logement', 'libelle' => 'Appartement']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Niveau Scolaire', 'libelle' => 'Bac pro']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Niveau Scolaire', 'libelle' => 'Bac+2']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Niveau Scolaire', 'libelle' => 'Bac+3/4']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Niveau Scolaire', 'libelle' => 'Collège']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Niveau Scolaire', 'libelle' => 'Bac+5']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'Niveau Scolaire', 'libelle' => 'Bac+8']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'CSP', 'libelle' => 'Chomage -1AN']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'CSP', 'libelle' => 'Chomage +1AN']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'CSP', 'libelle' => 'Salarié(e)']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'CSP', 'libelle' => 'Scolarisé(e)']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'CSP', 'libelle' => 'Retraité(e)']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'CSP', 'libelle' => 'Partenaire']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'CSP', 'libelle' => 'Descolarisé']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'CSP', 'libelle' => 'Personne au foyer']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'CSP', 'libelle' => 'MDPH']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'CSP', 'libelle' => 'Formation']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'CSP', 'libelle' => 'Stagiaire']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'CSP', 'libelle' => 'Indemnité jounalière']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'CSP', 'libelle' => 'CADA']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'CSP', 'libelle' => 'Ne sais pas']);
        App\Configuration::create(['categorie' => 'Personne', 'champ' => 'CSP', 'libelle' => 'Autre']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Accompagnement', 'libelle' => 'Ponctuel']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Accompagnement', 'libelle' => 'Long-court']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'AS']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Renseignement']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Rédaction courrier']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Orientation']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Inscription']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Prise de rendez-vous']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Accueil']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Partenaire']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Recherche']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Suivi']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Téléchargement document']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Information']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Projet']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'E-déclaration']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Médiation']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Prévention individuelle']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Lettre de motivation']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Problemes Familiaux']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Formation recherche']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Appel']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Constitution dossier']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Mission local']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Pole emploi']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Droit et rédaction']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'ASE']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Service Mairie']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Association']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'CFA/Centre de formation']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'CIO']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'PLI']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Maison du droit']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Interfamiliale']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Conseil Départemental']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'DDCS']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'DLA']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'FOL']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Culture du Coeur']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Assurance']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Projet']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'MDPH']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Etablissement scolaire/Crèche']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'ALJ']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => '115 Urgence']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'CCAS']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'CAF']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Impots']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Sécurité social']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Retraite']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Elus']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Planning familial']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'CMP/CMPP']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Commissariat']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Préfecture']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Tribunal']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Prud\'Hommes']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Edf/gdf']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Bailleur social']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Banque']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Remplir doc cerfa']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Ecoute']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Employeur']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Explication de courriers']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'CV']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Scan/mail doc']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'E-procédure docs officiels']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Accès point numerique']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Maison des femmes']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Observatoire des violences faites aux femmes']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Unite médicale judiciaire']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Psychologue']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Candidatures par mail/inernet/']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Chambre du commerce']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Centre maternel']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Tuteur']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Secours populaire']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'Resto du coeur']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Dirigé vers', 'libelle' => 'SIAO']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Paiement en ligne']);
        App\Configuration::create(['categorie' => 'Action', 'champ' => 'Action', 'libelle' => 'Chèque énergie']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Mairie']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Type', 'libelle' => 'CAF']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Préfecture']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Association']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Culture du Poeur']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'CAF']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Justice']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Mission locale']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Tuteur/Curateur']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Pole emploi']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Education nationale']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'MDPH']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Centre de Formation']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Commissariat']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Stagiaire']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Plaine commune']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Type', 'libelle' => 'Cadre de vie']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Type', 'libelle' => 'Culturel']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Type', 'libelle' => 'Social']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Type', 'libelle' => 'Santé']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Type', 'libelle' => 'Jeunesse']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Type', 'libelle' => 'Education']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Type', 'libelle' => 'Emploi']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Type', 'libelle' => 'Logement']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Type', 'libelle' => 'Sport']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Type', 'libelle' => 'Sécurité']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Type', 'libelle' => 'Justice']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Prevention specialisee']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Université']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Entreprise privee']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Prestataire']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Politique de la ville']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Type', 'libelle' => 'Elu(e)']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Média Journaliste']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Type', 'libelle' => 'Journaliste']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Artistique']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Interlogement siao']);
        App\Configuration::create(['categorie' => 'Partenaire', 'champ' => 'Structure', 'libelle' => 'Centre maternel']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Catégorie', 'libelle' => 'Couple']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Catégorie', 'libelle' => 'Enfant']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Catégorie', 'libelle' => 'Enquérir']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Catégorie', 'libelle' => 'Formation']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Catégorie', 'libelle' => 'Citoyenneté']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Catégorie', 'libelle' => 'Consommation']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Catégorie', 'libelle' => 'Amendes']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Catégorie', 'libelle' => 'Transport']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Catégorie', 'libelle' => 'Hébergement']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Catégorie', 'libelle' => 'Emploi et revenus']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Catégorie', 'libelle' => 'Santé']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Catégorie', 'libelle' => 'Handicap']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Catégorie', 'libelle' => 'Réunion']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Catégorie', 'libelle' => 'Partenaire']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Catégorie', 'libelle' => 'Information']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Catégorie', 'libelle' => 'Justice']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Catégorie', 'libelle' => 'Prison']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Tension']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Violence']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'ASE']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'CAF']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Formation']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'MDPH']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'PJJ']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Scolarité']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Signalement']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Autre']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Salutation']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Offrir un cadeau']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Stage']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Recherche']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Actes(Décès)']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Nationalité']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Impot']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Droit Résidence']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Passeport/CNI']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Livret de Famille']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'B3']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Assurance']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Banque']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Abonnements']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Surendettement']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Biens divers']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Transport']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Routière']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Autres']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Escroquerie']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Courrier']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Titre de Transport']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Billet']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Solidarité Transport']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Améthyste Transport']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'DALO']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'FAJ(hotel']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'ASE(hotel)']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Litige(dette)']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Expulsion']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Dossier']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Allocation retour à l\'emploi']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Allocation solidarité spécifique']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Allocation temporaire d\'attente']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Caritatif']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'CCAS(aide)']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Conflit du W']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'FAJ(aide)']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Pole emploi']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Prime d\'activité']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Retraite']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'RSA']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Surrendettement']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'CMU']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'AME']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Soins généraux']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Dépistage']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Distribution']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Sécurité Social']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Psychiatrie']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Mutuelles']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Culture']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Social']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Santé']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Jeunesse']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Education']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Logement']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Sport']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Culturel']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Emploi']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Cadre de vie']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Sécurité']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Justice']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Information']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Ouverture de droit']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Maintien de droit']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Judiciarisation']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Conflit']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Detenu']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Edf/gdf']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Renouv doss']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Actualisation']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Dossier bourse']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Permis']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Glissement de bail']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Bailleur/hlm']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Creation entreprise']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Mission locale']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Déclaration de ressources']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Navigo/amethyste']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'APL']);
        App\Configuration::create(['categorie' => 'Problème', 'champ' => 'Type', 'libelle' => 'Media']);
        App\Configuration::create(['categorie' => 'Caf', 'champ' => 'Motif', 'libelle' => 'Téléprocédure accompagnée']);
        App\Configuration::create(['categorie' => 'Caf', 'champ' => 'Motif', 'libelle' => 'Impression attestation de droits et/ou de QF']);
        App\Configuration::create(['categorie' => 'Caf', 'champ' => 'Motif', 'libelle' => 'Information générale sur la Caf et/ou les prestations']);
        App\Configuration::create(['categorie' => 'Caf', 'champ' => 'Motif', 'libelle' => 'Explication d\'un courrier']);
        App\Configuration::create(['categorie' => 'Caf', 'champ' => 'Motif', 'libelle' => 'Rédaction d\'un courrier, mail']);
        App\Configuration::create(['categorie' => 'Caf', 'champ' => 'Motif', 'libelle' => 'Complétude et/ou vérification d\'un dossier avant envoie']);
        App\Configuration::create(['categorie' => 'Caf', 'champ' => 'Motif', 'libelle' => 'Vers autre mode de contrat Caf']);
        App\Configuration::create(['categorie' => 'Caf', 'champ' => 'Motif', 'libelle' => 'Autre orientation']);
        App\Configuration::create(['categorie' => 'Caf', 'champ' => 'Motif', 'libelle' => 'Commentaire ou autre action']);
    }
}
